/* eslint-disable no-multi-spaces */
export enum MoviesTypes {
  REQUEST_MOVIES       = 'REQUEST_MOVIES',
  FETCH_MOVIES_START   = 'FETCH_MOVIES_START',
  FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS',
  FETCH_MOVIES_ERROR   = 'FETCH_MOVIES_ERROR',
  ADD_MOVIES = 'ADD_MOVIES',
  SET_RESULTS_COUNT = 'SET_RESULTS_COUNT',
  SET_LOADING = 'SET_LOADING',
  SET_PAGE = 'SET_PAGE',
}
/* eslint-enable no-multi-spaces */
