/* eslint-disable no-multi-spaces */
export enum MoviesTypes {
  REQUEST_MOVIES_BY_QUERY          = 'REQUEST_MOVIES_BY_QUERY',
  FETCH_MOVIES_BY_QUERY_START      = 'FETCH_MOVIES_BY_QUERY_START',
  FETCH_MOVIES_BY_QUERY_SUCCESS    = 'FETCH_MOVIES_BY_QUERY_SUCCESS',
  FETCH_MOVIES_BY_QUERY_ERROR      = 'FETCH_MOVIES_BY_QUERY_ERROR',
  CLEAR_MOVIES_BY_QUERY            = 'CLEAR_MOVIES_BY_QUERY',

  REQUEST_MOVIE_BY_ID              = 'REQUEST_MOVIE_BY_ID',
  FETCH_MOVIE_BY_ID_START          = 'FETCH_MOVIE_BY_ID_START',
  FETCH_MOVIE_BY_ID_SUCCESS        = 'FETCH_MOVIE_BY_ID_SUCCESS',
  FETCH_MOVIE_BY_ID_ERROR          = 'FETCH_MOVIE_BY_ID_ERROR',

  REQUEST_RELATED_MOVIES           = 'REQUEST_RELATED_MOVIES',
  FETCH_RELATED_MOVIES_START       = 'FETCH_RELATED_MOVIES_START',
  FETCH_RELATED_MOVIES_SUCCESS     = 'FETCH_RELATED_MOVIES_SUCCESS',
  FETCH_RELATED_MOVIES_ERROR       = 'FETCH_RELATED_MOVIES_ERROR',

  REQUEST_MOVIES_BY_CATEGORY       = 'REQUEST_MOVIES_BY_CATEGORY',
  FETCH_MOVIES_BY_CATEGORY_START   = 'FETCH_MOVIES_BY_CATEGORY_START',
  FETCH_MOVIES_BY_CATEGORY_SUCCESS = 'FETCH_MOVIES_BY_CATEGORY_SUCCESS',
  FETCH_MOVIES_BY_CATEGORY_ERROR   = 'FETCH_MOVIES_BY_CATEGORY_ERROR',
}
/* eslint-enable no-multi-spaces */
