/* eslint-disable no-multi-spaces */
export enum SearchTypes {
  REQUEST_SEARCH_RESULTS       = 'REQUEST_SEARCH_RESULTS',
  FETCH_SEARCH_RESULTS_START   = 'FETCH_SEARCH_RESULTS_START',
  FETCH_SEARCH_RESULTS_SUCCESS = 'FETCH_SEARCH_RESULTS_SUCCESS',
  FETCH_SEARCH_RESULTS_ERROR   = 'FETCH_SEARCH_RESULTS_ERROR',
}
/* eslint-enable no-multi-spaces */
