/* eslint-disable no-multi-spaces */
export enum ShowsTypes {
  REQUEST_SHOWS_BY_QUERY          = 'REQUEST_SHOWS_BY_QUERY',
  FETCH_SHOWS_BY_QUERY_START      = 'FETCH_SHOWS_BY_QUERY_START',
  FETCH_SHOWS_BY_QUERY_SUCCESS    = 'FETCH_SHOWS_BY_QUERY_SUCCESS',
  FETCH_SHOWS_BY_QUERY_ERROR      = 'FETCH_SHOWS_BY_QUERY_ERROR',
  CLEAR_SHOWS_BY_QUERY            = 'CLEAR_SHOWS_BY_QUERY',

  REQUEST_SHOW_BY_ID              = 'REQUEST_SHOW_BY_ID',
  FETCH_SHOW_BY_ID_START          = 'FETCH_SHOW_BY_ID_START',
  FETCH_SHOW_BY_ID_SUCCESS        = 'FETCH_SHOW_BY_ID_SUCCESS',
  FETCH_SHOW_BY_ID_ERROR          = 'FETCH_SHOW_BY_ID_ERROR',

  REQUEST_RELATED_SHOWS           = 'REQUEST_RELATED_SHOWS',
  FETCH_RELATED_SHOWS_START       = 'FETCH_RELATED_SHOWS_START',
  FETCH_RELATED_SHOWS_SUCCESS     = 'FETCH_RELATED_SHOWS_SUCCESS',
  FETCH_RELATED_SHOWS_ERROR       = 'FETCH_RELATED_SHOWS_ERROR',

  REQUEST_SHOWS_BY_CATEGORY       = 'REQUEST_SHOWS_BY_CATEGORY',
  FETCH_SHOWS_BY_CATEGORY_START   = 'FETCH_SHOWS_BY_CATEGORY_START',
  FETCH_SHOWS_BY_CATEGORY_SUCCESS = 'FETCH_SHOWS_BY_CATEGORY_SUCCESS',
  FETCH_SHOWS_BY_CATEGORY_ERROR   = 'FETCH_SHOWS_BY_CATEGORY_ERROR',
}
/* eslint-enable no-multi-spaces */
