/* eslint-disable no-multi-spaces */
export enum PersonsTypes {
  REQUEST_POPULAR_PERSONS       = 'REQUEST_POPULAR_PERSONS',
  FETCH_POPULAR_PERSONS_START   = 'FETCH_POPULAR_PERSONS_START',
  FETCH_POPULAR_PERSONS_SUCCESS = 'FETCH_POPULAR_PERSONS_SUCCESS',
  FETCH_POPULAR_PERSONS_ERROR   = 'FETCH_POPULAR_PERSONS_ERROR',

  REQUEST_PERSON_BY_ID          = 'REQUEST_PERSON_BY_ID',
  FETCH_PERSON_BY_ID_START      = 'FETCH_PERSON_BY_ID_START',
  FETCH_PERSON_BY_ID_SUCCESS    = 'FETCH_PERSON_BY_ID_SUCCESS',
  FETCH_PERSON_BY_ID_ERROR      = 'FETCH_PERSON_BY_ID_ERROR',
}
/* eslint-enable no-multi-spaces */
